### ISSUE TITLE
trying to pip install fuzzysearch, and it installed succeed, but cant find the name find_near_matches

### ISSUE THREAD

**Issue by jarodtang** [taleinat/fuzzysearch#12]
Hi ,

I'm trying to pip install fuzzysearch, and it installed succeed, but cant find the name find_near_matches, is it changed or else?

Thanks,
Jarod
```

$ sudo pip install fuzzysearch

Requirement already satisfied: fuzzysearch in /Library/Python/2.7/site-packages
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from fuzzysearch)

>>> from fuzzysearch import find_near_matches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fuzzysearch.py", line 4, in <module>
    from fuzzysearch import find_near_matches, Match
ImportError: cannot import name find_near_matches
>>> 


```

**Comment by jarodtang** [comment]
The installing process as following ( on mac )

```
$ sudo pip install fuzzysearch

Collecting fuzzysearch
  Downloading fuzzysearch-0.5.0-cp27-cp27m-macosx_10_12_x86_64.whl (60kB)
    100% |████████████████████████████████| 61kB 45kB/s 
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from fuzzysearch)
Installing collected packages: fuzzysearch
Successfully installed fuzzysearch-0.5.0


$ python 
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fuzzysearch import find_near_matches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fuzzysearch.py", line 4, in <module>
    from fuzzysearch import find_near_matches, Match
ImportError: cannot import name find_near_matches
>>> 
```

**Comment by taleinat** [comment]
Seems like this was a user error: `fuzzysearch.py` doen't exist in this library, so it must have been a file created by @jarodtang, which was being imported instead of the intended `fuzzysearch` package.
